version: "3"
services:
  web:
    build: apache
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./starwars:/app/starwars
      - ./startrek:/app/startrek
      - ./palpatine:/app/palpatine
      - ./apache/startrek.conf:/etc/apache2/sites-enabled/startrek.conf
      - ./apache/starwars.conf:/etc/apache2/sites-enabled/starwars.conf
